### ISSUE TITLE
Return the information about rate limits for calls

### ISSUE THREAD

**Issue by javiermarasco** [bitvavo/python-bitvavo-api#15]
This wrapper is great, awesome work there!!.
Currently I am working in implementing some tracking information for my transactions but while checking the documentation I found this:

On each REST request, there are three headers that return relevant information:

Bitvavo-Ratelimit-ResetAt: Timestamp when counter resets.
Bitvavo-Ratelimit-Limit: Your weighted allowed ratelimit.
Bitvavo-Ratelimit-Remaining: Your allowed weight left until the counter resets.

But using the python module I was unable to find a way to get those headers, will this be implemented? or it is already implemented and I am missing something?

Thank you!!

**Comment by rroumenov** [comment]
Hi @javiermarasco ,
if you check out the functions `publicRequest` and `privateRequest` and print  `r.headers` you would see the information you want and a little bit more.
Check out that `updateRateLimit` if called passing `r.headers` as parameter, and inside with its values, `self.rateLimitReset` and `self.rateLimitRemaining` variables are updated.
So, if you have your `bitvavo = Bitvavo()` object, you just need to use `bitvavo.rateLimitRemaining` and `bitvavo.rateLimitReset` to get what you need.
The RateLimit is always the same (1000 per minute).

Regards

**Comment by javiermarasco** [comment]
@rroumenov Thank you very much for the response (and very quick also!) I found it and implemented it huge tanks again!
