### ISSUE TITLE
on_open() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by djdino56** [bitvavo/python-bitvavo-api#16]
After a change in the websocket client (release `0.58.0`) with the following commit: https://github.com/websocket-client/websocket-client/commit/40e3a937381ea01137266b081e8ebb0e5a251c63

I got the following error:
`on_open() takes 1 positional argument but 2 were given` 

This is because the on_open in the bitvavo repo only takes 1 parameter.
https://github.com/bitvavo/python-bitvavo-api/blob/fea9d99dcbb1f9d3dadd1a3cae4e99eb432fe642/python_bitvavo_api/bitvavo.py#L536

### More information

1. File and line number on websocket-client repo:
https://github.com/websocket-client/websocket-client/blob/910e6e14c64a664c3432db2f5fd9f1395dc9e7f7/websocket/_app.py#L388
2. Release history: https://pypi.org/project/websocket-client/0.58.0/#history

**Comment by djdino56** [comment]
Using `websocket-client===0.57.0` fixed the issue for now.

**Comment by joeri-vv** [comment]
I've updated the setup file which builds for pypi to specify `websocket-client==0.57.0`, thanks!
