### ISSUE TITLE
How can I get the error codes? 

### ISSUE THREAD

**Issue by abirjameel** [bitvavo/python-bitvavo-api#24]
As the wrapper code is not fully open-source I believe and not available here, and I have to get all the error codes to develop an application using websocket. Please guide how can I find them

**Comment by NostraDavid** [comment]
Here is a list of error codes anyway: https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/bitvavo.py#L190

Don't know how ccxt got them, but they did.
