### ISSUE TITLE
The pair keys/Ip are not functioning

### ISSUE THREAD

**Issue by ilnegro** [bitvavo/python-bitvavo-api#7]
I set API keys and put my ip address but, when I use them I get this error:
{'errorCode': 307, 'error': 'This key does not allow access from this IP.'}

**Comment by joeri-vv** [comment]
The error specifies exactly what is going wrong here, Your API key does not allow access from your IP address.
This is because you applied IP whitelisting when you created your API key, but apparently are using a different IP to request from.
